### ISSUE TITLE
Add OAuth2 and RPC support

### ISSUE THREAD

**Issue by Azoy** [Azoy/Sword#11]
- [x] OAuth2
- [ ] RPC

**Comment by nullpixel1** [comment]
I'll look into adding OAuth, as I may find it useful for a iOS app I'm working on

**Comment by Azoy** [comment]
@nullpixel1 I plan to work on OAuth implementation this week. I'll let you know when I have something ready for release.

**Comment by Azoy** [comment]
RPC could be something we look into the future, but as for now that API is private.
