### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by SciencyScience** [Azoy/Sword#20]
Garys-iMac:DiscordClient ryder$ swift package generate-xcodeproj
warning: refname '0.5.5' is ambiguous.
warning: refname '0.5.5' is ambiguous.
HEAD is now at 3282baf Add logger (early)
Resolved version: 0.5.5
/Users/ryder/Desktop/Xcode Projects/DiscordClient/Packages/Sword/Package.swift:46:3: error: argument 'swiftLanguageVersions' must precede argument 'dependencies'
  swiftLanguageVersions: [3],
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
  dependencies: dependencies
Can't parse Package.swift manifest file because it contains invalid format. Fix Package.swift file format and try again.
error: The package at `/Users/ryder/Desktop/Xcode Projects/DiscordClient/Packages/Sword' has no Package.swift for the specific version: 0.5.5

**Comment by Azoy** [comment]
swiftLanguageVersions must come before dependencies in Package.swift

Try `rm -rf .build`, then build after you’ve done everything.

**Comment by SciencyScience** [comment]
Sorry it took so long to respond. I already tried that (before I saw this), and nothing happened. I'm currently updating xcode. Will update when/

**Comment by SciencyScience** [comment]
Updated xcode and swift, it works now! Sorry for wasting your time.
