### ISSUE TITLE
Is it Possible to Login From a User (non-bot) Account?

### ISSUE THREAD

**Issue by Stunner** [Azoy/Sword#35]
I see from your example and from the methods in Sword.swift that authentication is intended for bots. Is it possible to log in regular users with this library? If so how? If not let me know and I'll gladly attempt to implement that functionality (some tips and pointers would be greatly appreciated).

**Comment by Azoy** [comment]
It is not currently possible. I wish for this functionality to be left out of the library because there are lots of talks about removing this ability. Maybe in the future I might change my mind, but right now I wish to leave this out.
