### ISSUE TITLE
Fix reconnecting

### ISSUE THREAD

**Issue by Azoy** [Azoy/Sword#36]
It appears that some users are experiencing reconnecting logic to not function properly.

**Comment by itslukej** [comment]
luke was here

**Comment by nullpixel** [comment]
did you ever figure this out? I can look into this tomorrow

**Comment by itslukej** [comment]
<@80351110224678912>

**Comment by Azoy** [comment]
@nullpixel I mean, from the testing I've done, it works, but I guess not. /shrug

**Comment by nullpixel** [comment]
hmm, the logic looks fine. well, this is the only other issue open and I really don’t want to work with Linux and swift so

**Comment by Azoy** [comment]
@nullpixel do it, you won't

**Comment by nullpixel** [comment]
I’ve alrwady used swift on Linux. Has it gotten any better?

**Comment by Azoy** [comment]
@nullpixel I thought it to be a problem with `nohup` itself, so if you can try testing with screen or something that would be appreciated

**Comment by nullpixel** [comment]
👍 Ubuntu?

**Comment by Azoy** [comment]
yea

**Comment by Azoy** [comment]
Fixed in https://github.com/Azoy/Sword/commit/92b8809e9d0e7ec9afb904ad9737337ac20cb526
