### ISSUE TITLE
Error importing Sodium

### ISSUE THREAD

**Issue by camielverdult** [Azoy/Sword#39]
import Sodium
       ^
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/camiel/Desktop/Swifty/.build/debug.yaml main

**Comment by Azoy** [comment]
Do you have sodium installed? `brew update && brew install libsodium` ?

**Comment by camielverdult** [comment]
I did a reinstall recently, Sodium was not installed. Thanks!
