### ISSUE TITLE
"Sockets" not found

### ISSUE THREAD

**Issue by ElijahZAwesome** [Azoy/Sword#44]
When I try to build using the default settings from the installation tutorial, I get "Sockets" not found twice. I tried adding more dependencies like BlueSocket but it's not working. Any help?

**Comment by MrLotU** [comment]
Can you tell what line the  error appears on? Also, if it's an issue with BlueSocket, you should talk to them if there are issues :)

**Comment by ElijahZAwesome** [comment]
Doesn't specify the line, its in the initial build process, separate from main.swift, its in Package.swift. It simply says:

`error: product dependency 'Sockets' not found`

after cloning all of the repositories.

**Comment by MrLotU** [comment]
Ah, in that case, can you send your Package.swift file contents?

**Comment by ElijahZAwesome** [comment]
Its simply the default from https://sword.azoy.me

but here:
`// swift-tools-version:4.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "executable name",
    dependencies: [
        .package(url: "https://github.com/Azoy/Sword", from: "0.9.0"),
    ],
    targets: [
        .target(
            name: "executable name",
            dependencies: ["Sword"]
        )
    ]
)
`

This is without BlueSocket, since it didn't help

**Comment by MrLotU** [comment]
So, I take it somewhere in your code you `import Sockets` if you remove that, you should be fine

**Comment by ElijahZAwesome** [comment]
1: I don't
2: That would break everything lmao

**Comment by MrLotU** [comment]
If you don't than you don't get the error you posted, `error: product dependency 'Sockets' not found` either means you have it in your dependencies, or have it in your project somewhere

**Comment by ElijahZAwesome** [comment]
I don't have it in my main.swift, but its everywhere in dependencies, and needs to be. Discord bots depend on WebSockets

**Comment by ElijahZAwesome** [comment]
that error is the only output

**Comment by Azoy** [comment]
@ElijahZAwesome Sorry this took me so long to respond. Can you try to use the `dev` branch? `.package(url: "https://github.com/Azoy/Sword", .branch("dev"))`?

**Comment by ElijahZAwesome** [comment]
works now, but as a side note im very confused on how to make sword work on iOS... anywhere else we can discuss that?

**Comment by zadojart** [comment]
The Discord API server, in the #swift_sword channel, would be ideal.
