### ISSUE TITLE
This library is written in Swift

### ISSUE THREAD

**Issue by s-coimbra21** [Azoy/Sword#45]
Hello,

I wanted to use this library but as soon as I cloned the repository, I noticed something quite tragic... the library is written in Swift!!

Please rewrite the project in JavaScript at your earliest convenience.

**Comment by Azoy** [comment]
We've taken careful consideration, and after hours of discussion we've decided to move forward with Swift.

**Comment by perryprog** [comment]
Has a Rust rewrite been considered? Rust is 100% memory safe and it's impossible to have bugs in it.

**Comment by FatalDizz** [comment]
If you want to interact with the discord api in other languages there are alternatives, I personally like swift and use this library as it is the best swift solution that runs on both OS X and Linux. Why demand a rewrite in a different language?
