### ISSUE TITLE
Can't generate xcodeproj file.

### ISSUE THREAD

**Issue by Oschly** [Azoy/Sword#46]
Hi
I have added to my project dependencies Sword, then ran `swift package update` and when I am trying to run `swift package generate-xcodeproj` I am getting an error:

`Fatal error: Duplicate values for key: 'Async': file /BuildRoot/Library/Caches/com.apple.xbs/Binaries/swiftlang/install/TempContent/Objects/BNI_assert_lightweight/swift-macosx-x86_64/stdlib/public/core/8/HashedCollections.swift, line 8108
[1]    21343 illegal hardware instruction  swift package generate-xcodeproj`

What can I do? I am on macOS Mojave 10.14 using newest Xcode 9.

**Comment by Azoy** [comment]
Hi, can you try using the dev branch? `.package(url: "https://github.com/Azoy/Sword", .branch("dev"))`, then after putting that into your `Package.swift`, can you run `rm -rf ./build && rm package.resolved && swift package generate-xcodeproj`?

**Comment by Oschly** [comment]
Dev branch is working. Thanks for the help!
