### ISSUE TITLE
Status "watching" not work

### ISSUE THREAD

**Issue by bart96-b** [Azoy/Sword#68]
`client.editStatus(to: Presence.Status.idle.rawValue, watching: "film")`

![image](https://user-images.githubusercontent.com/13605756/83679230-b4594880-a5e7-11ea-87c5-9f208f95807d.png)

**Comment by parataxis782** [comment]
Same thing

**Comment by Azoy** [comment]
https://github.com/Azoy/Sword/commit/71623e2c494d115ce529d0df8bb8080cd06442ae fixes this issue.
