### ISSUE TITLE
Documentation link in README redirects to spam site

### ISSUE THREAD

**Issue by aheze** [Azoy/Sword#72]
When I open the "Documentation" link...

<kbd>![Shot 2020-12-04 at 1 36 20 PM](https://user-images.githubusercontent.com/49819455/101217143-b4d5a900-3635-11eb-81da-f8b497c21878.png)</kbd>

... it either closes the tab immediately (probably my adblocker), or shows something like this:

![Shot 2020-12-04 at 1 35 56 PM](https://user-images.githubusercontent.com/49819455/101217188-ccad2d00-3635-11eb-9f00-8f8c648142e7.png) | ![Shot 2020-12-04 at 1 37 36 PM](https://user-images.githubusercontent.com/49819455/101217259-e77fa180-3635-11eb-93ee-e4bdc4133e54.png)
--- | ---

**Comment by Azoy** [comment]
Thanks, this is fixed now https://github.com/Azoy/Sword/commit/01185a232ea9a33f67711550f77a7a8dbca2dc78
